alias src="source /opt/ros/noetic/setup.bash && source /workspace/catkin_ws/devel/setup.bash"

alias cws="cd /workspace/catkin_ws"
alias bws="cws && catkin build && src"

alias killgazebo="pkill -9 gazebo & pkill -9 gzserver & pkill -9 gzclient & pkill -9 gazebo_gui"